config/routes.rb
Threestars::Application.routes.draw do
  resources :items

  root to: 'top#index'

  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure"            => "sessions#failure"
  get "/logout"                  => "sessions#destroy", as: :logout

  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :content

  scope :mine, ->(user) { where( items: { user_id: user.id } ) }

  validates :name, presence: true

  # スター表示
  def star_display
    ('★' * self.star.to_i) + '：' + Settings.star[self.star]
  end

  private

  # スター表示
  def self.star_display(star)
    ('★' * star.to_i) + '：' + Settings.star[star]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # auth情報更新
  def auth_update( auth )
    if auth["provider"] == "facebook"
      image_path = "https://graph.facebook.com/#{auth['info']['nickname'].presence || auth["uid"]}/picture?width=200&height=200"
    else
      image_path = auth["info"]["image"]
    end

    if self.name != auth["info"]["name"] or self.nickname != auth["info"]["nickname"] or self.image != image_path or self.email != auth["info"]["email"]
      self.name     = auth["info"]["name"]
      self.nickname = auth["info"]["nickname"]
      self.image    = image_path
      self.email    = auth["info"]["email"]
      self.gender   = auth["extra"]["raw_info"]["gender"]
      self.location = auth["info"]["location"] || auth["extra"]["raw_info"]["location"]
      self.save!
    end
  end

  private

  # auth情報登録
  def self.create_with_omniauth( auth )
    user = User.new
    user.provider = auth["provider"]
    user.uid      = auth["uid"]

    if auth["info"].present?
      user.name     = auth["info"]["name"]
      user.nickname = auth["info"]["nickname"]
      user.image    = auth["info"]["image"]
      user.email    = auth["info"]["email"]
      user.location = auth["info"]["location"]
    end

    if auth["credentials"].present?
      user.token  = auth['credentials']['token']
      user.secret = auth['credentials']['secret']
    end

    if auth["extra"].present? and auth["extra"]["raw_info"].present?
      user.gender   = auth["extra"]["raw_info"]["gender"]
      user.location = auth["extra"]["raw_info"]["location"] if user.location.blank?
    end

    user.save!

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate           # ログイン認証
  before_filter :reset_session_expires  # セッション有効期限延長

  private

  # ログイン認証
  def authenticate
    unless signed_in?
      # リクエストURL保管
      session[:request_url] = request.url

      # ルートヘリダイレクト
      redirect_to :root and return
    end
  end

  # セッション期限延長
  def reset_session_expires
    request.session_options[:expire_after] = 2.weeks
  end

  # ログインユーザ
  def current_user
    @current_user ||= User.where( id: session[:user_id] ).first
  end
  helper_method :current_user

  # ユーザ登録チェック
  def signed_in?
    User.where( id: session[:user_id] ).exists?
  end
  helper_method :signed_in?
end

app/controllers/items_controller.rb
# coding: utf-8
class ItemsController < ApplicationController
  permits :user_id, :category_id, :content_id, :star, :name, :done_date

  # GET /items
  def index(category_id, star)
    @item = Item.new(star: 0, category_id: Category.find_by(name: 'その他').try(:id))
    @items = Item.mine(current_user).order(done_date: :desc)
    @items.where!(category_id: category_id) if category_id.present?
    @items.where!(star: star)               if star.present?

    @category_id = category_id
    @star        = star
  end

  # # GET /items/1
  # def show(id)
  #   @item = Item.mine(current_user).find_by(id: id)
  # end

  # # GET /items/new
  # def new
  #   @item = Item.new(star: 0, category_id: Category.find_by(name: 'その他').try(:id))
  # end

  # GET /items/1/edit
  def edit(id)
    @item = Item.mine(current_user).find_by(id: id)
  end

  # POST /items
  def create(item)
    @item = Item.new(item.permit!)
    @item.user_id = current_user.id

    if @item.save
      # redirect_to @item, notice: 'コンテンツ履歴を作成しました。'
      redirect_to items_path, notice: 'コンテンツ履歴を作成しました。'
    else
      render action: 'new'
    end
  end

  # PUT /items/1
  def update(id, item)
    @item = Item.mine(current_user).find_by(id: id)

    if @item.update(item)
      # redirect_to @item, notice: 'コンテンツ履歴を更新しました。'
      redirect_to items_path, notice: 'コンテンツ履歴を更新しました。'
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  def destroy(id)
    @item = Item.mine(current_user).find_by(id: id)
    @item.destroy

    redirect_to items_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate

  # ログイン
  def callback
    auth = request.env["omniauth.auth"]

    user = User.where( provider: auth["provider"], uid: auth["uid"] ).first || User.create_with_omniauth( auth )
    user.auth_update( auth )

    session[:user_id] = user.id

    # 保管URLへリダイレクト
    unless session[:request_url].blank?
      redirect_to session[:request_url]
      session[:request_url] = nil
      return
    end

    redirect_to items_path, notice: "ログインしました。"
  end

  # ログアウト
  def destroy
    session[:user_id] = nil

    redirect_to :root, notice: "ログアウトしました。"
  end

  # ログインエラー
  def failure
    render text: "<span style='color: red;'>Auth Failure</span>"
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_filter :authenticate

  # トップ
  def index
    # ログイン済みはリダイレクト
    redirect_to items_path and return if current_user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
- if item.errors.any?
  #error_explanation
    %h2= "#{pluralize(item.errors.count, "error")} prohibited this item from being saved:"
    %ul
      - item.errors.full_messages.each do |msg|
        %li= msg
.field
  = f.label :name, 'コンテンツ名'
  = f.text_field :name, size: 50

.field
  = f.label :category_id, 'カテゴリ：'
  - Category.all.each do |category|
    = f.radio_button :category_id, category.id,{ checked: (item.category_id == category.id) }
    = f.label "category_id_#{category.id}", category.name

.field
  = f.label :star, '評価：'
  - (0..3).each do |rank|
    = f.radio_button :star, rank,{ checked: (item.star == rank) }
    = f.label "star_#{rank}", ('☆' * rank) + '：' + Settings.star[rank]

.field
  = f.label :done_date, '完了日'
  = f.date_select :done_date

app/views/items/edit.html.haml
%h1 Editing item

= form_for @item do |f|
  = render partial: '/items/form', locals: { f: f, item: @item }
  / - if @item.errors.any?
  /   #error_explanation
  /     %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
  /     %ul
  /       - @item.errors.full_messages.each do |msg|
  /         %li= msg
  / .field
  /   = f.label :name, 'コンテンツ名'
  /   = f.text_field :name, size: 50

  / .field
  /   = f.label :category_id, 'カテゴリ'
  /   - Category.all.each do |category|
  /     %li
  /       = f.radio_button :category_id, category.id,{ checked: (@item.category_id == category.id) }
  /       = f.label "category_id_#{category.id}", category.name
  / / .field
  / /   = f.label :content
  / /   = f.text_field :content
  / .field
  /   = f.label :star, '評価'
  /   - (1..3).each do |rank|
  /     %li
  /       = f.radio_button :star, rank,{ checked: (@item.star == rank) }
  /       = f.label "star_#{rank}", ('☆' * rank) + '：' + Settings.star[rank]
  / .field
  /   = f.label :done_date, '完了日'
  /   = f.date_select :done_date
  .actions
    = f.submit '保存', data: { disable_with: '保存...' }

%br
= link_to 'Show', @item
\|
= link_to 'Back', items_path

app/views/items/index.html.haml
%h1= link_to 'コンテンツ履歴一覧', items_path

= form_for @item do |f|
  = render partial: '/items/form', locals: { f: f, item: @item }
  .actions
    = f.submit '保存', data: { disable_with: '保存...' }

%hr
%br

%table
  %tr
    %th{ colspan: Category.all.length + 1 } カテゴリ
  %tr
    %td= link_to 'すべて', items_path(category_id: nil, star: @star)
    - Category.all.each do |category|
      %td= link_to_unless (@category_id == category.id.to_s), category.name, items_path(category_id: category.id, star: @star)
%br

%table
  %tr
    %th{ colspan: 5 } 評価
  %tr
    %td= link_to 'すべて', items_path(star: nil, category_id: @category_id)
    - (0..3).each do |star|
      %td= link_to_unless (@star == star.to_s), Item.star_display(star), items_path(star: star, category_id: @category_id)

%p= "#{@items.to_a.length}件"

%table
  %tr
    %th ユーザ
    %th カテゴリ
    / %th Content
    %th 評価
    %th コンテンツ名
    %th 完了日
    / %th
    %th
    %th

  - @items.each do |item|
    %tr
      %td= render partial: '/layouts/user_icon', locals: { user: item.user, size: "18x18", klass: "margin_minus2" }
      %td= item.category.try(:name)
      / %td= item.content
      %td= item.star_display
      / %td= item.name
      %td= link_to item.name, "http://www.amazon.co.jp/s/ref=nb_sb_noss_2?__mk_ja_JP=カタカナ&url=search-alias%3Daps&field-keywords=#{item.name}&at=#{Settings.amazon_affiliate_id}", target: '_blank'
      %td= item.done_date.strftime("%Y年%m月%d日") if item.done_date.present?
      / %td= link_to '詳細', item
      %td= link_to '編集', edit_item_path(item)
      %td= link_to '削除', item, method: :delete, data: { confirm: "「#{item.name}」を削除します。よろしいですか？" }

%br

/ = link_to '新規作成', new_item_path

app/views/layouts/_user_icon.html.haml
- if user.present?
  = link_to_unless( user.nickname.blank?, image_tag( user.image, size: size, class: klass ), "#{Settings[user.provider + '_page']}#{user.nickname}", target: "_blank", title: user.nickname, rel: "tooltip", "data-original-title" => user.nickname )

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Settings.app_name
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body{ 'data-no-turbolink' => true }
    = link_to Settings.app_name, :root
    - if signed_in?
      = render partial: '/layouts/user_icon', locals: { user: current_user, size: "18x18", klass: "margin_minus2" }
      = link_to( "トップ", root_path )
      = link_to( "コンテンツ履歴", items_path )
      = link_to( "ログアウト", logout_path )
    - else
      %br
      %br
      ログイン:
      \#{link_to "Twitter", "/auth/twitter"}
      / \#{link_to "Facebook", "/auth/facebook"}
      / \#{link_to "GitHub", "/auth/gitHub"}
    = simple_format( flash[:notice], style: "color: green;" ) if flash[:notice].present?
    = simple_format( flash[:alert], style: "color: red;" ) if flash[:alert].present?
    = yield
    %br/
    %br/
    %center
      Developed by
      = succeed "," do
        %a{:href => "https://twitter.com/#{Settings.programmer_twitter_id}/", :target => "_blank"}
          @#{Settings.programmer_twitter_id}
      Designed by
      = succeed "," do
        %a{:href => "https://twitter.com/#{Settings.designer_twitter_id}/", :target => "_blank"}
          @#{Settings.designer_twitter_id}
      Licence by
      %a{:href => "https://creativecommons.org/licenses/by-nc-sa/2.1/jp/", :target => "_blank"} CC BY-NC-SA 2.1

app/views/top/index.html.haml
%h1
  Welcome to #{Settings.app_name}.